// Generated by gencpp from file lab5/MoveBotRequest.msg
// DO NOT EDIT!


#ifndef LAB5_MESSAGE_MOVEBOTREQUEST_H
#define LAB5_MESSAGE_MOVEBOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab5
{
template <class ContainerAllocator>
struct MoveBotRequest_
{
  typedef MoveBotRequest_<ContainerAllocator> Type;

  MoveBotRequest_()
    : i(0)
    , j(0)  {
    }
  MoveBotRequest_(const ContainerAllocator& _alloc)
    : i(0)
    , j(0)  {
  (void)_alloc;
    }



   typedef int32_t _i_type;
  _i_type i;

   typedef int32_t _j_type;
  _j_type j;




  typedef boost::shared_ptr< ::lab5::MoveBotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab5::MoveBotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveBotRequest_

typedef ::lab5::MoveBotRequest_<std::allocator<void> > MoveBotRequest;

typedef boost::shared_ptr< ::lab5::MoveBotRequest > MoveBotRequestPtr;
typedef boost::shared_ptr< ::lab5::MoveBotRequest const> MoveBotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab5::MoveBotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab5::MoveBotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lab5

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lab5::MoveBotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab5::MoveBotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab5::MoveBotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab5::MoveBotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab5::MoveBotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab5::MoveBotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab5::MoveBotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a7c168ffcde5af04d198a3bd6eb9076";
  }

  static const char* value(const ::lab5::MoveBotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a7c168ffcde5af0ULL;
  static const uint64_t static_value2 = 0x4d198a3bd6eb9076ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab5::MoveBotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab5/MoveBotRequest";
  }

  static const char* value(const ::lab5::MoveBotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab5::MoveBotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 i\n\
int32 j\n\
";
  }

  static const char* value(const ::lab5::MoveBotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab5::MoveBotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.i);
      stream.next(m.j);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MoveBotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab5::MoveBotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab5::MoveBotRequest_<ContainerAllocator>& v)
  {
    s << indent << "i: ";
    Printer<int32_t>::stream(s, indent + "  ", v.i);
    s << indent << "j: ";
    Printer<int32_t>::stream(s, indent + "  ", v.j);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB5_MESSAGE_MOVEBOTREQUEST_H
