// Generated by gencpp from file lab5/Position.msg
// DO NOT EDIT!


#ifndef LAB5_MESSAGE_POSITION_H
#define LAB5_MESSAGE_POSITION_H

#include <ros/service_traits.h>


#include <lab5/PositionRequest.h>
#include <lab5/PositionResponse.h>


namespace lab5
{

struct Position
{

typedef PositionRequest Request;
typedef PositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Position
} // namespace lab5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab5::Position > {
  static const char* value()
  {
    return "e08ef57940873b4e7c6ae9af91d65b85";
  }

  static const char* value(const ::lab5::Position&) { return value(); }
};

template<>
struct DataType< ::lab5::Position > {
  static const char* value()
  {
    return "lab5/Position";
  }

  static const char* value(const ::lab5::Position&) { return value(); }
};


// service_traits::MD5Sum< ::lab5::PositionRequest> should match 
// service_traits::MD5Sum< ::lab5::Position > 
template<>
struct MD5Sum< ::lab5::PositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab5::Position >::value();
  }
  static const char* value(const ::lab5::PositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab5::PositionRequest> should match 
// service_traits::DataType< ::lab5::Position > 
template<>
struct DataType< ::lab5::PositionRequest>
{
  static const char* value()
  {
    return DataType< ::lab5::Position >::value();
  }
  static const char* value(const ::lab5::PositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab5::PositionResponse> should match 
// service_traits::MD5Sum< ::lab5::Position > 
template<>
struct MD5Sum< ::lab5::PositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab5::Position >::value();
  }
  static const char* value(const ::lab5::PositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab5::PositionResponse> should match 
// service_traits::DataType< ::lab5::Position > 
template<>
struct DataType< ::lab5::PositionResponse>
{
  static const char* value()
  {
    return DataType< ::lab5::Position >::value();
  }
  static const char* value(const ::lab5::PositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB5_MESSAGE_POSITION_H
