# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lab4/Observation.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Observation(genpy.Message):
  _md5sum = "b962468f892f707011ae231ec4acdeb5"
  _type = "lab4/Observation"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 timeTag
int32 tagNum
float64 range
geometry_msgs/Quaternion bearing

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['timeTag','tagNum','range','bearing']
  _slot_types = ['int32','int32','float64','geometry_msgs/Quaternion']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timeTag,tagNum,range,bearing

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Observation, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timeTag is None:
        self.timeTag = 0
      if self.tagNum is None:
        self.tagNum = 0
      if self.range is None:
        self.range = 0.
      if self.bearing is None:
        self.bearing = geometry_msgs.msg.Quaternion()
    else:
      self.timeTag = 0
      self.tagNum = 0
      self.range = 0.
      self.bearing = geometry_msgs.msg.Quaternion()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2i5d.pack(_x.timeTag, _x.tagNum, _x.range, _x.bearing.x, _x.bearing.y, _x.bearing.z, _x.bearing.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.bearing is None:
        self.bearing = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.timeTag, _x.tagNum, _x.range, _x.bearing.x, _x.bearing.y, _x.bearing.z, _x.bearing.w,) = _struct_2i5d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2i5d.pack(_x.timeTag, _x.tagNum, _x.range, _x.bearing.x, _x.bearing.y, _x.bearing.z, _x.bearing.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.bearing is None:
        self.bearing = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.timeTag, _x.tagNum, _x.range, _x.bearing.x, _x.bearing.y, _x.bearing.z, _x.bearing.w,) = _struct_2i5d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2i5d = struct.Struct("<2i5d")
